django_tweet_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("tweet_app.urls")),
]

tweet_app/urls.py
from django.urls import path, include
from . import views

app_name = "tweet_app"

urlpatterns = [
    path('', views.index, name="index"),
    path('listtweet', views.listtweet, name="listtweet"),
    path('addtweet', views.addtweet, name="addtweet"),
    path('addtweetbyform', views.AddTweetByForm, name="addtweetbyform"),
]

tweet_app/models.py
from django.db import models

class tweet(models.Model):
    nickname = models.CharField(max_length=50)
    message = models.CharField(max_length=100)
    def __str__(self):
        return f"Nickname : {self.nickname}, Message : {self.message}"

tweet_app/forms.py
from django import forms

class AddTweetForms(forms.Form):
    nickname_input = forms.CharField(label="Nickname", max_length=5)
    message_input = forms.CharField(label="Message", max_length=10)

tweet_app/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from . import models
from django.urls import reverse
from tweet_app.forms import AddTweetForms

def index(request):
    return render(request, "tweet_app/first.html")

def addtweet(request):
    if request.POST:
        nickname = request.POST["nickname"]
        message = request.POST["message"]
        models.tweet.objects.create(nickname=nickname, message=message)
        return redirect(reverse('tweet_app:listtweet'))
    else:
        return render(request, "tweet_app/addtweet.html")


def listtweet(request):
    all_tweet = models.tweet.objects.all()
    tweet_dic = {"tweets":all_tweet}
    return render(request, "tweet_app/listtweet.html", context=tweet_dic)

def AddTweetByForm(request):

    if request.POST:
        form = AddTweetForms(request.POST)
        if form.is_valid():
            nickname = form.cleaned_data["nickname_input"]
            message = form.cleaned_data["message_input"]
            models.tweet.objects.create(nickname=nickname, message=message)
            return redirect(reverse('tweet_app:listtweet'))
        else:
            print("error in form")
            return render (request, "tweet_app/addtweetbyform.html", context={"form":form})
    else:
        form = AddTweetForms()
        return render (request, "tweet_app/addtweetbyform.html", context={"form":form})

templates/base.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>TWEET APP</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
    <style>
        .bd-placeholder-img {
          font-size: 1.125rem;
          text-anchor: middle;
          -webkit-user-select: none;
          -moz-user-select: none;
          user-select: none;
        }
  
        @media (min-width: 768px) {
          .bd-placeholder-img-lg {
            font-size: 3.5rem;
          }
        }
  
        .b-example-divider {
          width: 100%;
          height: 3rem;
          background-color: rgba(0, 0, 0, .1);
          border: solid rgba(0, 0, 0, .15);
          border-width: 1px 0;
          box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
        }
  
        .b-example-vr {
          flex-shrink: 0;
          width: 1.5rem;
          height: 100vh;
        }
  
        .bi {
          vertical-align: -.125em;
          fill: currentColor;
        }
  
        .nav-scroller {
          position: relative;
          z-index: 2;
          height: 2.75rem;
          overflow-y: hidden;
        }
  
        .nav-scroller .nav {
          display: flex;
          flex-wrap: nowrap;
          padding-bottom: 1rem;
          margin-top: -1px;
          overflow-x: auto;
          text-align: center;
          white-space: nowrap;
          -webkit-overflow-scrolling: touch;
        }
  
        .btn-bd-primary {
          --bd-violet-bg: #712cf9;
          --bd-violet-rgb: 112.520718, 44.062154, 249.437846;
  
          --bs-btn-font-weight: 600;
          --bs-btn-color: var(--bs-white);
          --bs-btn-bg: var(--bd-violet-bg);
          --bs-btn-border-color: var(--bd-violet-bg);
          --bs-btn-hover-color: var(--bs-white);
          --bs-btn-hover-bg: #6528e0;
          --bs-btn-hover-border-color: #6528e0;
          --bs-btn-focus-shadow-rgb: var(--bd-violet-rgb);
          --bs-btn-active-color: var(--bs-btn-hover-color);
          --bs-btn-active-bg: #5a23c8;
          --bs-btn-active-border-color: #5a23c8;
        }
        .bd-mode-toggle {
          z-index: 1500;
        }
      </style>
</head>
<body>
    <header>
        <!-- Fixed navbar -->
        <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
          <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'tweet_app:addtweet' %}">Add Tweet</a>
            <a class="navbar-brand" href="{% url 'tweet_app:listtweet' %}">List Tweet</a>
            <a class="navbar-brand" href="{% url 'tweet_app:addtweetbyform' %}">Add Tweet By</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
              <ul class="navbar-nav me-auto mb-2 mb-md-0">
                <li class="nav-item">
                  <a class="nav-link active" aria-current="page" href="{% url 'tweet_app:listtweet' %}"></a>
                </li>
              </ul>
            </div>
          </div>
        </nav>
      </header>

      {% block content %}
      
      {% endblock content %}
    
</body>
</html>

tweet_app/templates/tweet_app/addtweet.html
{% extends 'base.html' %}

{% block content %}
    <br><br><br>
    <h1>Add Tweet App</h1>

    <form action="" method="POST">
        {% csrf_token %}
        <div class="container">
          <label for="nickname" class="form-label">Nickname</label>
          <input type="text" class="form-control" id="exampleInputEmail1" name="nickname">
        </div>
        <div class="container">
          <label for="message" class="form-label">Message</label>
          <input type="text" class="form-control" id="message" name="message">
        </div>
        <div class="container">
          <button type="submit" class="btn btn-primary", style="padding: 10px;">Send Tweet</button>
        </div>
        
      </form>

{% endblock content %}

tweet_app/templates/tweet_app/addtweetbyform.html
{% extends 'base.html' %}

{% block content %}
    <br><br><br>
    <h1>Add Tweet By Form</h1>

    <form action="" method="POST">
        {% csrf_token %}
        
        {{form.as_p}}
        <button type="submit" class="btn btn-primary">Send Tweet</button>
{% endblock content %}

tweet_app/templates/tweet_app/first.html
{% extends 'base.html' %}

{% block content %}
    <br><br><br>
    <h1>deneme index</h1>

{% endblock content %}

tweet_app/templates/tweet_app/listtweet.html
{% extends 'base.html' %}

{% block content %}
    <br><br><br>
    <h1>List Tweet App</h1>
    {% for data in tweets %}
       <ul>{{data.nickname}} ---> {{data.message}}</ul>
    {% endfor %}
    
{% endblock content %}